config/routes.rb
Rails.application.routes.draw do

  resources :offers do
    collection do
      get :new_search
      get :search
    end
  end
  root 'offers#new_search'
end

app/models/offer.rb
class Offer
  attr_accessor :title, :payout, :thumbnail

  def initialize(attrs = {})
    self.title      = attrs[:title]
    self.payout     = attrs[:payout]
    self.thumbnail  = attrs[:thumbnail]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def search
    result = RetrieveOffers.call(pub0: params[:pub0], uid: params[:uid], page: params[:page])
    if result.success?
      @offers = result.offers
    else
      if result.error == 'API_INTERNAL_ERROR'
        @errors = ['There was an error in the Fyber API. Try again later.']
      else
        @errors = [result.message]
      end
    end
  end

  def new_search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileOffersApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/_new_search_form.html.haml
.panel.panel-default
  .panel-heading
    %h5 Fill out the input paramters for offers
  .panel-body
    = form_tag(search_offers_path, method: 'get') do
      .form-group
        %label{ for: 'uid' }
          uid
        = text_field_tag 'uid', attrs[:uid], class: 'form-control', placeholder: 'eg., user1', required: true
      .form-group
        %label{ for: 'pub0' }
          pub0
        = text_field_tag 'pub0', attrs[:pub0], class: 'form-control', placeholder: 'eg., campaign1', required: true
      .form-group
        %label{ for: 'page' }
          page
        = text_field_tag 'page', attrs[:page], class: 'form-control', placeholder: 'eg., 1', required: true
      %button.btn.btn-success{ type: 'submit' }
        %span.glyphicon.glyphicon-search
        Search

app/views/offers/new_search.html.haml
.row
  .col-md-3
    = render partial: 'offers/new_search_form', locals: { attrs: {} }

app/views/offers/search.html.haml
.row
  .col-md-3
    = render partial: 'offers/new_search_form', locals: { attrs: { uid: params[:uid], pub0: params[:pub0], page: params[:page] } }
  .col-md-9
    - if @errors.present?
      .panel.panel-danger
        .panel-body
          %ul
            - @errors.each do |error|
              %li
                = error
    - else
      .panel.panel-default
        .panel-heading
          Found #{@offers.count} offers
        .panel-body
          - if @offers.present?
            %table.table.table-striped.table-hover
              %thead
                %tr
                  %th #
                  %th Title
                  %th Payout
                  %th Thumbnail
              %tbody
                - @offers.each_with_index do |offer, index|
                  %tr
                    %td=(index+1)
                    %td=offer.title
                    %td=offer.payout
                    %td
                      %img.offer-thumbnail{ src: offer.thumbnail }
          - else
            %p
              %em No offers found with the search parameters